### ISSUE TITLE
build spin on windows error

### ISSUE THREAD

**Issue by pengliaoye** [fermyon/spin-componentize#1]
error: failed to run custom build command for `spin-componentize v0.1.0 (https://github.com/fermyon/spin-componentize#cf15f8a3)`

error[E0463]: can't find crate for `core`

**Comment by dicej** [comment]
Thanks for the report!  Have you tried running `rustup target add wasm32-unknown-unknown` (and also `rustup target add wasm32-wasi` if necessary)?  `spin-componentize` depends on both.  See also https://github.com/fermyon/developer/pull/515

I can also add some build instructions to the README.md in this repo.

**Comment by dicej** [comment]
I just updated the README.md.

**Comment by pengliaoye** [comment]
resolved. thanks
